routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // return view('welcome');
// });

Auth::routes();
Route::get('/','AdminController@index');
Route::resource('/product', 'ProductController');
Route::resource('/categori', 'ProductCategoriController');
Route::resource('/transaction', 'TransactionController');
Route::get('transaction/{id}/set-status','TransactionController@setstatus')->name('status');
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function galeries()
    {
        return $this->hasMany(ProductGalerie::class);
    }
    public function category()
    {
        return $this->belongsTo(ProductCategori::class, 'category_id', 'id');
    }
}

app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductCategori;
class ProductController extends Controller
{
    public function all(Request $request)
    {
        $id = $request->input('id');
        $limit = $request->input('limit',6);
        $name = $request->input('name');
        $slug = $request->input('slug');
        $price_from = $request->input('price_from');
        $price_to = $request->input('price_to');

       if ($id) {
           $product = Product::with('category','galeries')->find($id);
           if ($product) {
                return ResponseFormated::success($product,'data berhasil di tambahkan');
           }else {
               return ResponseFormated::error($product,'data gagal di tambahkan',404);
           }
       }
       if ($slug) {
           $product = Product::with('category','galeries')->where('slug',$slug)->first();
           if ($product) {
                return ResponseFormated::success($product,'data berhasil di tambahkan');
           }else {
               return ResponseFormated::error($product,'data gagal di tambahkan',404);
           }
       }
       $product = Product::with('category','galeries');
       if ($name) {
           $product->where('name','like','%'.$name.'%');
       }
       if ($price_from) {
           $product->where('price', '>=', $price_from);
       }
       if ($price_to) {
        $product->where('price', '<=', $price_to);
       }
       return ResponseFormated::success(
           $product->paginate($limit),'data berhasil di tambahkan'
       );
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProductRequest;
use Illuminate\Support\Str;
use App\Models\Product;
use App\Models\ProductGalerie;
use App\Models\ProductCategori;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $record = Product::with('galeries')->get();
        return view('pages.product.index',[
            'record' => $record
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $record = ProductCategori::get();
        return view('pages.product.create',['record' => $record]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        if ($request->hasFile('photo')) {
            $photo = $request->file('photo')->store('assets/product','public');
        }
        $barang = Product::create([
            'name' => $request->name,
            'slug' => str::slug($request->name),
            'category_id' => $request->category_id,
            'description' => $request->description,
            'price' => $request->price,
            'quantity' => $request->quantity,
        ]);
        $barang->galeries()->create([
            'photo' => $photo,
            'is_default'=> true
        ]);
        return redirect('product');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = ProductCategori::get();
        return view('pages.product.edit',[
            'record' => Product::find($id),
            'kategori' => $kategori
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $photo = null;
        if ($request->hasFile('photo')) {
            $photo = $request->file('photo')->store('assets/product','public');
        }
        $data = Product::findOrFail($id);
        $barang = $data->update([
            'name' => $request->name,
            'slug' => str::slug($request->name),
            'category_id' => $request->category_id,
            'description' => $request->description,
            'price' => $request->price,
            'quantity' => $request->quantity,
        ]);
        $data->galeries()->create([
            'photo' => $photo,
            'is_default'=> true
        ]);
        return redirect('product');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        $product->galeries()->delete();
        return redirect('product');
    }
}

resources/views/pages/product/create.blade.php
@extends('layouts.default')
@section('content')
    <div class="card">
        <h4 class="card-header">Tambah Product</h4>
        <div class="card-body">
            <form action="{{ url('product') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="">Nama Barang</label>
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Nama Barang" value="{{ old('name') }}">
                    @error('name')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                {{-- <div class="form-group">
                    <label for="">Tyoe Barang</label>
                    <input type="text" name="type" class="form-control @error('type') is-invalid @enderror" placeholder="Type Barang" value="{{ old('type') }}">
                    @error('type')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div> --}}
                <div class="form-group">
                    <label for="">Kategori</label>
                    <select name="category_id" id="" class="form-control">
                        <option value="">Pilih Kategori</option>
                        @foreach ($record as $item)
                            <option value="{{ $item->id }}">{{ $item->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Description</label>
                    <textarea name="description" id="editor" cols="30" rows="10" class="form-control @error('description') is-invalid @enderror">{{ old('description') }}</textarea>
                    @error('description')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Harga Barang</label>
                    <input type="number" name="price" class="form-control @error('price') is-invalid @enderror" placeholder="Harga Barang" value="{{ old('price') }}">
                    @error('price')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Quantity Barang</label>
                    <input type="number" name="quantity" class="form-control @error('quantity') is-invalid @enderror" placeholder="Harga Barang" value="{{ old('quantity') }}">
                    @error('quantity')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Picture</label>
                    <input type="file" name="photo" id="" class="form-control @error('photo') is-invalid @enderror" accept="image/*">
                    @error('photo')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary btn-block">Simpan</button>
            </form>
        </div>
    </div>
@endsection
@push('ckeditor')
<script src="https://cdn.ckeditor.com/ckeditor5/23.0.0/classic/ckeditor.js"></script>
    <script type="text/javascript">
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .then( editor => {
                    console.log( editor );
            } )
            .catch( error => {
                    console.error( error );
            });
    </script>
@endpush

resources/views/pages/product/edit.blade.php
@extends('layouts.default')
@section('content')
    <div class="card">
        <h4 class="card-header">Tambah Product</h4>
        <div class="card-body">
            <form action="{{ url('product',$record->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <input type="hidden" name="id" value="{{ $record->id }}">
                <div class="form-group">
                    <label for="">Nama Barang</label>
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Nama Barang" value="{{ $record->name }}">
                    @error('name')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Kategori</label>
                    <select name="category_id" id="" class="form-control">
                        <option value="">Pilih Kategori</option>
                        @foreach ($kategori as $item)
                            <option value="{{ $item->id }}" {{ $record->category_id == $item->id ? 'selected' : '' }}>{{ $item->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Description</label>
                    <textarea name="description" id="editor" cols="30" rows="10" class="form-control @error('description') is-invalid @enderror">{{ $record->description }}</textarea>
                    @error('description')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Harga Barang</label>
                    <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" placeholder="Harga Barang" value="{{ $record->price }}">
                    @error('price')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Quantity Barang</label>
                    <input type="text" name="quantity" class="form-control @error('quantity') is-invalid @enderror" placeholder="Harga Barang" value="{{ $record->quantity }}">
                    @error('quantity')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="card-body">
                    <div class="row">
                        @if ($record->galeries->count() > 0)
                            @foreach ($record->galeries as $gam)
                                <div class="col-lg-4">
                                    <div class="text-center">
                                        <img src="{{ $gam->photo }}" alt="" height="150">
                                    </div>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label for="">Picture</label>
                    <input type="file" name="photo" id="" class="form-control @error('photo') is-invalid @enderror" accept="image/*">
                    @error('photo')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
    </div>
@endsection
@push('ckeditor')
<script src="https://cdn.ckeditor.com/ckeditor5/23.0.0/classic/ckeditor.js"></script>
    <script type="text/javascript">
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .then( editor => {
                    console.log( editor );
            } )
            .catch( error => {
                    console.error( error );
            });
    </script>
@endpush

resources/views/pages/product/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="orders">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Daftar Product</h4>
                    </div>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama</th>
                                        <th>Kategori</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Photo</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $no = 1; ?>
                                    @foreach ($record as $item)
                                        <tr>
                                            <td>{{ $no }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->category->nama }}</td>
                                            <td>{{ $item->price }}</td>
                                            <td>{{ $item->quantity }}</td>
                                            @if ($item->galeries->count() > 0)
                                                <td><img src="{{ $item->galeries->first()->photo }}" alt=""></td>
                                            @endif
                                            {{-- @foreach ($item->galeries as $items)
                                                <td><img src="{{ $items->photo ?? '' }}" alt=""></td>
                                            @endforeach --}}
                                            <td>
                                                <a href="" class="btn btn-sm btn-info">
                                                    <i class="fa fa-picture-o"></i>
                                                </a>
                                                <a href="{{ url("product/$item->id/edit") }}" class="btn btn-sm btn-primary">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <form action="{{ route('product.destroy',$item->id) }}" method="post" class="d-inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                        <?php $no++ ?>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection