routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // return view('welcome');
// });

Auth::routes();
Route::get('/','AdminController@index');
Route::resource('/product', 'ProductController');
Route::resource('/categori', 'ProductCategoriController');
Route::resource('/transaction', 'TransactionController');
Route::get('transaction/{id}/set-status','TransactionController@setstatus')->name('status');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/pages/categori/create.blade.php
@extends('layouts.default')
@section('content')
    <div class="card">
        <h4 class="card-header">Tambah Categori</h4>
        <div class="card-body">
            <form action="{{ url('categori') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" placeholder="Nama Barang" value="{{ old('nama') }}">
                    @error('nama')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary btn-block">Simpan</button>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/categori/edit.blade.php
@extends('layouts.default')
@section('content')
    <div class="card">
        <h4 class="card-header">Tambah Categori</h4>
        <div class="card-body">
            <form action="{{ url('categori',$record->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" placeholder="Nama Barang" value="{{ $record->nama }}">
                    @error('nama')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary btn-block">Simpan</button>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/categori/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="orders">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Daftar Product</h4>
                    </div>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Slug</th>
                                        <th>Nama</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if ($record->count() > 0)
                                        <?php $no = 1; ?>
                                        @foreach ($record as $item)
                                            <tr>
                                                <td>{{ $no }}</td>
                                                <td>{{ $item->slug }}</td>
                                                <td>{{ $item->nama }}</td>
                                                <td>
                                                    <a href="{{ url("categori/$item->id/edit") }}" class="btn btn-sm btn-primary">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <form action="{{ route('categori.destroy',$item->id) }}" method="post" class="d-inline">
                                                        @csrf
                                                        @method('delete')
                                                        <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                            <?php $no++ ?>
                                        @endforeach
                                        @else
                                        <tr>
                                            <td>Data Masih Kosong</td>
                                        </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection