routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // return view('welcome');
// });

Auth::routes();
Route::get('/','AdminController@index');
Route::resource('/product', 'ProductController');
Route::resource('/categori', 'ProductCategoriController');
Route::resource('/transaction', 'TransactionController');
Route::get('transaction/{id}/set-status','TransactionController@setstatus')->name('status');
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/API/TransactionController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Transaction;
class TransactionController extends Controller
{
    public function detail(Request $request, $id)
    {
        $product = Transaction::with('details.product')->find($id);

        if ($product) {
            return ResponseFormated::success($product,'Data berhasil di ambil');
        }else {
            return ResponseFormated::error(null,'Data Gagal  di ambil',404);
        }
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Transaction;
class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $record = Transaction::get();
        return view('pages.transaction.index',['record' => $record]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $record = Transaction::with('details.product')->findOrFail($id);
        return view('pages.transaction.show',['record' => $record]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('pages.transaction.edit',[
            'record' => Transaction::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $record = Transaction::findOrFail($id);
        $record->update($data);
        return redirect('transaction');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = Transaction::findOrFail($id);
        $record->delete();
        return redirect('transaction');
    }

    public function setstatus(Request $request, $id)
    {
        $request->validate([
            'status' => 'required|in:PENDING,SUCCESS,FAILED'
        ]);

        $record = Transaction::findOrFail($id);
        $record->transaction_status = $request->status;
        $record->save();
        return redirect('transaction');
    }
}

resources/views/pages/transaction/edit.blade.php
@extends('layouts.default')
@section('content')
    <div class="card">
        <h4 class="card-header">Update Transaksi</h4>
        <div class="card-body">
            <form action="{{ url('transaction',$record->id) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Masukan Nmaa.." value="{{ old('name') ?? $record->name }}">
                    @error('name')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Email</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="email" placeholder="Masukan Nmaa.." value="{{ old('email') ?? $record->email }}">
                    @error('email')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Number</label>
                    <input type="text" class="form-control @error('number') is-invalid @enderror" name="number" placeholder="Masukan Nmaa.." value="{{ old('number') ?? $record->number }}">
                    @error('number')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Address</label>
                    <input type="text" class="form-control @error('address') is-invalid @enderror" name="address" placeholder="Masukan Nmaa.." value="{{ old('address') ?? $record->address }}">
                    @error('address')
                        <div class="text-muted">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary btn-block">Simpan</button>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/transaction/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="orders">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Daftar Transaksi</h4>
                    </div>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>uuid</th>
                                        <th>Nama</th>
                                        <th>Number</th>
                                        <th>address</th>
                                        <th>Transaksi total</th>
                                        <th>Status</th>
                                        <th>action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $no = 1; ?>
                                    @foreach ($record as $item)
                                        <tr>
                                            <td>{{ $no }}</td>
                                            <td>{{ $item->uuid }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->number }}</td>
                                            <td>{{ $item->address }}</td>
                                            <td>{{ 'Rp '. number_format($item->transaction_total,2,',','.') }}</td>
                                            <td>
                                                @switch($item->transaction_status)
                                                    @case('PENDING')
                                                        <span class="badge badge-primary">PENDING</span>
                                                        @break
                                                    @case('SUCCESS')
                                                        <span class="badge badge-success">SUCCESS</span>
                                                        @break
                                                    @case('FAILED')
                                                        <span class="badge badge-warning">FAILED</span>
                                                        @break
                                                    @default

                                                @endswitch
                                            </td>
                                            <td>
                                                @if ($item->transaction_status == 'PENDING')
                                                <a href="{{ route('status',$item->id) }}?status=SUCCESS" class="btn btn-success btn-sm">
                                                <i class="fa fa-check"></i>
                                                </a>
                                                <a href="{{ route('status',$item->id) }}?status=FAILED" class="btn btn-warning btn-sm">
                                                <i class="fa fa-times"></i>
                                                </a>
                                                @endif
                                                <a href="#mymodal" data-remote="{{ url('transaction',$item->id) }}" data-target="#mymodal" data-toggle="modal" data-title="Detail Transaksi {{ $item->uuid }}" class="btn btn-sm btn-info">
                                                    <i class="fa fa-eye"></i>
                                                </a>
                                                <a href="{{ url("transaction/$item->id/edit") }}" class="btn btn-sm btn-primary">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <form action="{{ route('transaction.destroy',$item->id) }}" method="post" class="d-inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                        <?php $no++ ?>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" id="mymodal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal" aria-label="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{-- <button type="button" class="close" data-dismiss="modal" aria-label="close">
                        <span aria-hidden="true">&times;</span>
                      </button> --}}
                    <h5 class="modal-title"></h5>
                </div>
                <div class="modal-body">
                    <i class="fa fa-spinner fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/transaction/show.blade.php
<table class="table table-bordered">
    <tr>
        <th>Nama</th>
        <td>{{ $record->name }}</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>{{ $record->email }}</td>
    </tr>
    <tr>
        <th>Number</th>
        <td>{{ $record->number }}</td>
    </tr>
    <tr>
        <th>Address</th>
        <td>{{ $record->address }}</td>
    </tr>
    <tr>
        <th>Transaksi</th>
        <td>{{ $record->transaction_total }}</td>
    </tr>
    <tr>
        <th>Status</th>
        <td>{{ $record->transaction_status }}</td>
    </tr>
    <tr>
        <th>Pembelian Product</th>
        <td>
            <table class="table table-bordered w-100">
                <tr>
                    <th>Nama</th>
                    <th>Kategori</th>
                    <th>Harga</th>
                </tr>
                @foreach ($record->details as $detail)
                @php
                    $product = App\Models\ProductCategori::where('id',$detail->product->category_id)->first();
                @endphp
                <tr>
                    <td>{{ $detail->product->name }}</td>
                    <td>{{ $product->nama }}</td>
                    <td>{{ $detail->product->price }}</td>
                </tr>
                @endforeach
            </table>
        </td>
    </tr>
</table>
<div class="row">
    <div class="col-4">
        <a href="{{ route('status',$record->id) }}?status=SUCCESS" class="btn btn-success btn-sm btn-block">
            <i class="fa fa-check"></i>Set Success
        </a>
    </div>
    <div class="col-4">
        <a href="{{ route('status',$record->id) }}?status=FAILED" class="btn btn-warning btn-sm btn-block">
            <i class="fa fa-times"></i>Set Gagal
        </a>
    </div>
    <div class="col-4">
        <a href="{{ route('status',$record->id) }}?status=PENDING" class="btn btn-primary btn-sm btn-block">
            <i class="fa fa-spinner"></i>Set Pending
        </a>
    </div>
</div>